stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: alfahumadocker/nextjs-otobos-services
  CONTAINER_NAME: nextjs-otobos-services
  APP_PORT: 13300

build:
  stage: build
  only:
   - development
  tags:
   - dev-malang
  script:
    - cp ${env_otobos} .env.production
    - rm -rf public/uploads/*
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  only:
   - development
  tags:
   - dev
  script:
    - docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME
    # Run new container
    - docker run --pull always -d --name=$CONTAINER_NAME -v /var/www/dev.alfahuma.tech/public_html/OTOBOS/next_otobos/uploads:/app/public/uploads -p 13300:3000 $DOCKER_IMAGE
